name: Docker build and push

on:
  workflow_dispatch:
  push:
    branches:
    - issues/93-launch-failure

jobs:
  buildandpush:
    uses: lsc-sde/lsc-sde/.github/workflows/docker-release.yaml@main
    with:
      imageName: jh-93
      directory: docker/jupyterhub
    secrets: inherit
